development:
    secret_token: insecure_test_token
    secret_key_base: insecure_test_base

production:
    secret_token: <%= ENV["SECRET_TOKEN"] %>
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
